# nix-pack.toml

[build]
# Command to install Docker Compose
install = "curl -L https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d '\"' -f 4)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose"

# Command to build the Docker Compose services
command = "docker-compose build"

[run]
# Command to start the Docker Compose services
command = "docker-compose up -d"

# Expose port 8443
ports = ["8443:8443"]
